FROM ros:foxy-ros-base

# Install required dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-pip python3-colcon-common-extensions git \
    libgl1 libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

# Workspace Setup
WORKDIR /ws
COPY . /ws

# Build dependencies and workspace
RUN bash -lc "source /opt/ros/foxy/setup.bash && colcon build --merge-install"

# Set environment variables
ENV ROS_DISTRO=foxy \
    RMW_IMPLEMENTATION=rmw_fastrtps_cpp \
    ROS_LOCALHOST_ONLY=0

# Default command to launch ROS nodes
CMD bash -lc "source /opt/ros/foxy/setup.bash && source /ws/install/setup.bash && ros2 launch obstacle_avoidance pub_launch.py"
